services:
  safeflood:
    container_name: safeflood
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    stdin_open: true    # keep STDIN open
    tty: true           # allocate a pseudo‐TTY
    command: tail -f /dev/null   # never exit