name: Deploy Reflex App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          app_directory: "." # Optional, defaults to root
          extra_args: "--env OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" # Optional
          python_version: "3.10" # Optional
